spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beatlayer
    username: beatlayer
    password: beatlayer
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080
