services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: beatlayer
      POSTGRES_PASSWORD: beatlayer
      POSTGRES_DB: beatlayer
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports: ["9000:9000", "9001:9001"]
    volumes: [miniodata:/data]

volumes:
  dbdata:
  miniodata:
